// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNeKpt-ftmvOsVQmVHiO09sRmasK-GJc',
    appId: '1:335121324798:web:8d0c88430475ae6aca63af',
    messagingSenderId: '335121324798',
    projectId: 'fitnesstracker-bfad2',
    authDomain: 'fitnesstracker-bfad2.firebaseapp.com',
    storageBucket: 'fitnesstracker-bfad2.firebasestorage.app',
    measurementId: 'G-48F9K3KH45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcAd8iniklubbh5mtEE-SYdbIf68P5-YQ',
    appId: '1:335121324798:android:5ad5fa4e7c585bacca63af',
    messagingSenderId: '335121324798',
    projectId: 'fitnesstracker-bfad2',
    storageBucket: 'fitnesstracker-bfad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibSJpCPlhPUZSSN2ikqZUgs6TYvgNySs',
    appId: '1:335121324798:ios:3aefa93463e71624ca63af',
    messagingSenderId: '335121324798',
    projectId: 'fitnesstracker-bfad2',
    storageBucket: 'fitnesstracker-bfad2.firebasestorage.app',
    iosBundleId: 'com.example.task4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDibSJpCPlhPUZSSN2ikqZUgs6TYvgNySs',
    appId: '1:335121324798:ios:3aefa93463e71624ca63af',
    messagingSenderId: '335121324798',
    projectId: 'fitnesstracker-bfad2',
    storageBucket: 'fitnesstracker-bfad2.firebasestorage.app',
    iosBundleId: 'com.example.task4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADNeKpt-ftmvOsVQmVHiO09sRmasK-GJc',
    appId: '1:335121324798:web:b0af9998ab12ee56ca63af',
    messagingSenderId: '335121324798',
    projectId: 'fitnesstracker-bfad2',
    authDomain: 'fitnesstracker-bfad2.firebaseapp.com',
    storageBucket: 'fitnesstracker-bfad2.firebasestorage.app',
    measurementId: 'G-BLXMG1RJGV',
  );
}
